### PR TITLE
refactor `removeBucket`

### PR DESCRIPTION
**Pull request by trim21**

### CODE REVIEW

**Review by prakashsvmx — APPROVED** [review]
Tested.  :+1: 
Note: `This operation will only work if your bucket is empty.`

### Callback style:

```js
const bucketName = 'test-js-bucket-1'
s3Client.removeBucket(bucketName, function (e) {
  if (e) {
    return console.log(e.message)
  }
  console.log('Success')
})


```
### Async/Await
```js
const removeBucketTest = async () => {
  try {
    await s3Client.removeBucket(bucketName)
    console.log('Success')
  } catch (err) {
    console.log(err.message)
  }
}

removeBucketTest()
```

**Comment by prakashsvmx** [comment]
@trim21  could you please resolve the conflicts ?

**Comment by trim21** [comment]
I didn't remove overload `removeBucket(bucketName: string, callback: NoResultCallback): void` as you did for `listBuckets`

**Review by prakashsvmx — APPROVED** [review]

**Comment by trim21** [comment]
@kaankabalak

**Comment by prakashsvmx** [comment]
@kaankabalak  Could you please take a look ?

**Review by kaankabalak — APPROVED** [review]

**Pull request merged**
