### PR TITLE
cleanup: remove un-needed code in transformers.js, move to es6 style where possible

### PR DESCRIPTION
**Pull request by krishnasrinivas**

### CODE REVIEW

**Comment by harshavardhana** [comment]
Why not make this a comprehensive cleanup? - there are few more functions like getRegion which needs to be remove as well.

**Comment by krishnasrinivas** [comment]
fix for the bug #373, let me do that.

**Comment by harshavardhana** [comment]
LGTM :+1:

**Comment by krishnasrinivas** [comment]
Hey minio/minio-js,

Discover high quality jobs and connect with recruiters on LinkedIn.

- Krishna

Accept invite: https://www.linkedin.com/e/v2?e=0-iky2pxlg-7v&t=ssuw&ek=invite_guest&li=14&m=invite_guest&ts=india_a&sharedKey=468rIhkc&invitationId=6107539881196609536



You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iky2pxlg-7v&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEX606zPITmxAAAAVMJXU76GbTtNSpkwUatt5FdM69tpYZzs8XGmYPk96S-G0BAccswbqAwDKAPKx2ICbDUQPflMSCegSOyYtzsBCxw129KgiKxZ6GRwA0C9qhkDyWGFfKQCcV6PPfiWyTxuwbYsa6jnLBXxOg09DF0sMRewA5clqUrj79AYvYLj2FHVkF_7Kyn&eid=0-iky2pxlg-7v


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iky2pxlg-7v&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by harshavardhana** [comment]
@krishnasrinivas why is this automated message here from linkedin ?

**Comment by krishnasrinivas** [comment]
looks like linkedin has spammed all my contacts :-(

**Pull request merged**
