### PR TITLE
refactor: `makeBucket`

### PR DESCRIPTION
**Pull request by trim21**

### CODE REVIEW

**Comment by trim21** [comment]
security warnings are false positive...

**Comment by trim21** [comment]
resolve conflicts

**Comment by trim21** [comment]
@prakashsvmx would you mind review this PR and approve ci?

**Comment by prakashsvmx** [comment]
> @prakashsvmx would you mind review this PR and approve ci?
> 
> and looks like CodeQL workflow failed, do you have any idea how to fix this?

This is a false positive, I think I ignored it in the past, let me check again.

**Comment by trim21** [comment]
@prakashsvmx

**Review by prakashsvmx — APPROVED** [review]

**Comment by trim21** [comment]
@kaankabalak

**Pull request merged**
