### PR TITLE
Add support for cn-north-1 endpoint (#489)

### LINKED ISSUE #489: Implement AWS China region support
Our Javascript Client library should also support  AWS China region s3.cn-north-1.amazonaws.com.cn

It has been implemented in minio-go, implementation reference:  https://github.com/minio/minio-go/commit/190ac7b4b7e7ba8a669553674b748bdcace6c59e

### PR DESCRIPTION
**Pull request by mkainula**
This should fix #489 

#hacktoberfest

### CODE REVIEW

**Comment by harshavardhana** [comment]
Thanks for the PR @mkainula - We need to add a check separately in "isValidEndpoint" to allow for passing in china endpoint.

**Comment by mkainula** [comment]
isValidEndpoint("s3.cn-north-1.amazonaws.com.cn") will already return true, as it's a valid domain but doesn't match the '.amazonaws.com$' check.

**Comment by harshavardhana** [comment]
> isValidEndpoint("s3.cn-north-1.amazonaws.com.cn") will already return true, as it's a valid domain but doesn't match the '.amazonaws.com$' check.

Can you add a testcase for this?

**Comment by krishnasrinivas** [comment]
it will be good to do an actual test against china end point ... @harshavardhana do we have access/secret key?

**Comment by harshavardhana** [comment]
> it will be good to do an actual test against china end point ... @harshavardhana do we have access/secret key?

We have validated it with community help with minio-go and 'mc' .  FWIW china region access keys are hard to get there is some weird process.

**Comment by harshavardhana** [comment]
Merging this @mkainula - Thanks for your work.  Will write test case locally and merge.

**Pull request merged**
