### PR TITLE
change linter to eslint, fix codebase

### PR DESCRIPTION
**Pull request by brendanashworth**
This fixes https://github.com/minio/minio-js/issues/604.

It changes the linter to eslint (now replacement for JSC). Most of the linters work the same so it's not so much about the linter but the rule choices. It also now runs `gulp lint` during CI tests.

I chose rules that aligned with the current codebase, but at times when it wasn't consistent, I chose what I thought was more prevalent / looked better. For example, indentation is just a hodge podge, but it's better to have rules for it than it be different across the whole codebase. (thats why the third commit is LONG)

### CODE REVIEW

**Comment by krishnasrinivas** [comment]
@brendanashworth this is great, is there someway these indentation rules can be used by some tool like https://github.com/millermedeiros/esformatter which can indent the source?

**Comment by brendanashworth** [comment]
@krishnasrinivas yes! Eslint allows you to do [`eslint ... --fix`](http://eslint.org/docs/user-guide/command-line-interface#--fix), which will automatically fix all the indentation issues in the source according to the rules you give it. That's how I generated the last commit.

**Comment by brendanashworth** [comment]
thanks!

**Comment by krishnasrinivas** [comment]
> thanks!

no, thank you.

**Pull request merged**
