### PR TITLE
fix: don't use DEFAULT_REGION for listBuckets method

### LINKED ISSUE #1148: `listBuckets` ignores Client constructor `region`
`listBuckets` is always called with `us-east-1` region.

Stepping through the code attempting debug it shows it always calls makeRequest with the `DEFAULT_REGION` and `makeRequestStream` checks that is passed in and immediately takes the value from `DEFAULT_REGION` due to the `if (region) return _makeRequest(null, region)` right before `this.getBucketRegion(options.bucketName, _makeRequest)`.

Extra info:
MinIO VERSION: **2023-03-22T06:36:24Z**
Node version: **v16.20.0**
Yarn version: **1.22.19**
minio-js version: **7.1.0**

### PR DESCRIPTION
**Pull request by aldy505**
Closes #1148

Previously I remembered that I change this line of code to fix that issue. It turns out, I haven't.

Please try to test it with both S3 and MinIO backends.

### CODE REVIEW

**Comment by aldy505** [comment]
@prakashsvmx @kaankabalak

**Review by kaankabalak — APPROVED** [review]
Approved @aldy505, please feel free to assign reviewers to the PR going forward

**Review by kaankabalak — APPROVED** [review]

**Comment by prakashsvmx** [comment]
i need to validate this with AWS.

**Review by prakashsvmx — APPROVED** [review]

**Comment by aldy505** [comment]
@prakashsvmx Have you validate this with AWS S3?

**Review by prakashsvmx — APPROVED** [review]

**Pull request merged**
