### PR TITLE
fix wrong property: Initiator to RequestInitiator of upload when parseListMultipart

### PR DESCRIPTION
**Pull request by viettel-solutions**

### CODE REVIEW

**Comment by prakashsvmx** [comment]
Thank you. Will test and run the functional tests as well to provide an update.

**Comment by prakashsvmx** [comment]
@viettel-solutions  Please update the problem description and the context of the issue? 
Is this tested/validated against a valid minio server deployment like play.min.io ?

**Comment by thangcqUET** [comment]
@prakashsvmx Sorry for the late reply, i think i have a problem with server what i use to test. Looks like it has a problem. I'll check it again

**Comment by viettel-solutions** [comment]
@prakashsvmx Sorry for the late reply, i think i have a problem with server what i use to test. Looks like it has a problem. I'll check it again

**Comment by harshavardhana** [comment]
Too old PR, closing nothing pending on our end.

**Pull request closed without merging**
