### PR TITLE
getBucketRegion: non s3 regions we should still fetch bucket regions.

### PR DESCRIPTION
**Pull request by harshavardhana**
We shouldn't assume all regions for 'non-s3' to be 'us-east-1'.

### CODE REVIEW

**Comment by harshavardhana** [comment]
@krishnasrinivas - this change is not possible until we fix our tests and getBucketLocation to everything we do.

**Comment by krishnasrinivas** [comment]
travis failed

**Comment by krishnasrinivas** [comment]
review not complete yet

**Comment by harshavardhana** [comment]
> travis failed

Same problem of https v/s http failing.

**Comment by harshavardhana** [comment]
Done the issue is resolved.

**Pull request merged**
