### PR TITLE
Update source-map-support version

### PR DESCRIPTION
**Pull request by will3942**
When running tests using `minio-js` with Jest and jsdom it was throwing errors due to minio-js using an old version of `source-map-support`.

```
/Users/will3942/work/spotlightdata/nanowire-rubix/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:486
        throw new DOMException(DOMException.SYNTAX_ERR);
        ^
SyntaxError
    at XMLHttpRequest.open (/Users/will3942/work/spotlightdata/nanowire-rubix/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:486:15)
    at retrieveSourceMapURL (/Users/will3942/work/spotlightdata/nanowire-rubix/node_modules/minio/node_modules/source-map-support/source-map-support.js:61:9)
    at retrieveSourceMap (/Users/will3942/work/spotlightdata/nanowire-rubix/node_modules/minio/node_modules/source-map-support/source-map-support.js:86:26)
    at mapSourcePosition (/Users/will3942/work/spotlightdata/nanowire-rubix/node_modules/minio/node_modules/source-map-support/source-map-support.js:116:21)
    at wrapCallSite (/Users/will3942/work/spotlightdata/nanowire-rubix/node_modules/minio/node_modules/source-map-support/source-map-support.js:270:20)
    at /Users/will3942/work/spotlightdata/nanowire-rubix/node_modules/minio/node_modules/source-map-support/source-map-support.js:304:26
    at Array.map (native)
    at Function.prepareStackTrace (/Users/will3942/work/spotlightdata/nanowire-rubix/node_modules/minio/node_modules/source-map-support/source-map-support.js:303:24)
    at Function.captureStackTrace (<anonymous>)
    at S3Error.ExtendableError (/Users/will3942/work/spotlightdata/nanowire-rubix/node_modules/es6-error/dist/index.js:37:13)
```

### CODE REVIEW

**Comment by harshavardhana** [comment]
ping @krishnasrinivas

**Comment by will3942** [comment]
@krishnasrinivas Can you merge and bump the version to make a new release ASAP please

**Comment by krishnasrinivas** [comment]
travis failed with:
```
0.06s$ yarn
Node version 0.10.36 is not supported, please use Node.js 4.0 or higher.
```

wonder why it is trying with 0.10.36, maybe a temporary issue.

**Comment by harshavardhana** [comment]
> Node version 0.10.36 is not supported, please use Node.js 4.0 or higher.

```
Computing checksum with sha256sum
Checksums do not match: 'f35d30b092a41ae10b7165c458cad0a78f9950ea1dcfe0166aadfa2ed244526b' found, 'f65d5d4b7253ee29f3ba4edabd3473845075e43569bceea4267e7bf3e00ebb96' expected.
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
nvm: install v6.10.0 failed!
``` 

Perhaps because of this..

**Pull request merged**
