### PR TITLE
Port in documentation is a string, where client expects a number.

### PR DESCRIPTION
**Pull request by notthepoint**
So I changed documentation to reflect port as a number.

### CODE REVIEW

**Comment by harshavardhana** [comment]
Thanks a lot @notthepoint

**Comment by harshavardhana** [comment]
LGTM, Thanks :+1:

**Comment by harshavardhana** [comment]
@koolhead17 we need to fix this for https://docs.minio.io

**Comment by koolhead17** [comment]
Done @harshavardhana  Thanks @notthepoint 👍

**Comment by notthepoint** [comment]
Ace! np :)

**Pull request merged**
