### PR TITLE
[#726] implementation of SSE-C

### PR DESCRIPTION
**Pull request by mtsyganov**
Currently it is possible to put objects to minio with server side encryption by using metaData. Unfortunately it is not possible to get those server side encrypted objects back from minio. 

This PR solves the problem by adding to the getObject functions the metaData parameter.

### CODE REVIEW

**Comment by prakashsvmx** [comment]
Closing this. As the changes related to this are merged and released.

**Comment by appcoders** [comment]
@prakashsvmx  This has never been landed to master? Because it does not work in the current release at all. Always getting S3 errors as all X-Amz-Server-Side-Encryption-* keys are set in query instead of headers.
Changing the code in minio.js that getOpts is added as headers via prependXAMZMeta and dropping query completely leads to a working solution for encrypted files.

**Comment by appcoders** [comment]
Addition in other SDKs like Python headers are used for SSE options: 
https://github.com/minio/minio-py/blob/3d01781eb0fc14857e1e11014483cdfd0186cb36/examples/fget_object.py#L36
https://github.com/minio/minio-py/blob/c195bc93d42eebc82e98c0dcb38f7695ef88ff06/minio/sse.py#L49

**Comment by appcoders** [comment]
@mtsyganov  Did you ever try if (f)getObject works with encrypted files?

**Pull request closed without merging**
