### PR TITLE
putObject: put object read stream should precede size.

### LINKED ISSUE #353: putObject should have content length as last argument

### PR DESCRIPTION
**Pull request by harshavardhana**
Fixes #353

### CODE REVIEW

**Comment by harshavardhana** [comment]
@krishnasrinivas  - can you review this?

**Comment by krishnasrinivas** [comment]
will review this, hold on.

**Comment by krishnasrinivas** [comment]
looks fine. but you could have split this into two commits
* putObject related changes
* other changes to API.md

**Comment by harshavardhana** [comment]
> looks fine. but you could have split this into two commits
> 
> putObject related changes
> other changes to API.md

True since it was changing documentation for putObject() API.md anyways, i finished it in this commit.

**Comment by harshavardhana** [comment]
Merging.

**Pull request merged**
