### PR TITLE
Support for PresignGetObject() API

### PR DESCRIPTION
**Pull request by krishnasrinivas**

### CODE REVIEW

**Comment by krishnasrinivas** [comment]
ok, let me resend.

**Comment by harshavardhana** [comment]
can you squash both the patches?

**Comment by krishnasrinivas** [comment]
ok.

**Comment by krishnasrinivas** [comment]
darn. the git log says getPresignedUrl but the code has PresignGetObject()

**Comment by harshavardhana** [comment]
No you can "git commit --amend" and edit it.

**Pull request merged**
