### PR TITLE
ci: bump dependencies; remove node 12 and node 14

### PR DESCRIPTION
**Pull request by aldy505**
- Bump dependencies on CI to use latest versions
- Remove Node 12 and Node 14 tests, as we don't support them anymore. They're not maintained versions either.

On the `package.json` file, it is defined that the minimum of Node.js version is 16. So it makes sense to drop version 12 and 14.

https://github.com/minio/minio-js/blob/51cf376d29d805e8b2aae02653cf1779817409ad/package.json#L75-L77

### CODE REVIEW

**Comment by trim21** [comment]
should we also downgrade `@types/node` to v16？

**Comment by aldy505** [comment]
> should we also downgrade `@types/node` to v16？

@trim21 No need, right? We're bundling everything with Babel anyway.

**Comment by trim21** [comment]
> > should we also downgrade `@types/node` to v16？
> 
> @trim21 No need, right? We're bundling everything with Babel anyway.

we didn't bundle anything

**Comment by aldy505** [comment]
> > > should we also downgrade `@types/node` to v16？
> > 
> > 
> > @trim21 No need, right? We're bundling everything with Babel anyway.
> 
> we didn't bundle anything

I thought Babel was for transpiling to older Nodejs versions, no?

**Comment by aldy505** [comment]
> > > > > should we also downgrade `@types/node` to v16？
> > > > 
> > > > 
> > > > @trim21 No need, right? We're bundling everything with Babel anyway.
> > > 
> > > 
> > > we didn't bundle anything
> > 
> > 
> > I thought Babel was for transpiling to older Nodejs versions, no?
> 
> yes, transpiling only

Ah that should be good enough.

Can I have this reviewed, please? @kaankabalak @prakashsvmx

**Review by kaankabalak — APPROVED** [review]

**Review by prakashsvmx — APPROVED** [review]

**Comment by prakashsvmx** [comment]
the CI still looks for tests on old version of node 12 on windows/ubuntu
 `Test on node 12.x and ubuntu-latest`
`Test on node 12.x and windows-latest`

We will check this. @aldy505

**Comment by aldy505** [comment]
@prakashsvmx Hi, any updates?

**Comment by prakashsvmx** [comment]
I think it requires some admin access at the org level , i will check further.

**Comment by trim21** [comment]
should also remove file https://github.com/minio/minio-js/blob/master/src/internal/async.ts ....

**Comment by trim21** [comment]
also https://github.com/minio/minio-js/blob/114ba7a919223827142ae9f24da3ffe754fbc395/babel-register.js#L22C91-L22C103

**Pull request merged**
