### PR TITLE
Add objectExists method

### PR DESCRIPTION
**Pull request by jsnider2**
Add an "objectExists" method to test if an object is present or not. Modeled more or less after bucketExists.

### CODE REVIEW

**Comment by harshavardhana** [comment]
isn't statObject doing the same thing here @jsnider2 what is the need for a new API?

**Comment by jsnider2** [comment]
statObject treats an object that doesn't exist as a failure, which makes it difficult to use in a Promise.all() when specifically are looking which of a set of objects don't exist. That was my use case where I found myself making a wrapper around statObject that wouldn't bail at the first missing object. Sure I can (and did) hack around it with statObject but if I found myself doing it I figured others would/have as well.

**Comment by krishnasrinivas** [comment]
If we add an API to minio-js we have to add it to other libs as well to be consistent.

> but if I found myself doing it I figured others would/have as well.

We are not sure at this point if it is worth adding a new API for this instead of having a wrapper around statObject. We can merge this in future if it is indeed useful for a others too.

**Comment by jsnider2** [comment]
That's fair. Thanks for taking a look. I'll leave the branch in case you do want to merge in the future.

**Comment by krishnasrinivas** [comment]
> I'll leave the branch in case you do want to merge in the future.

that will be great, thanks!

**Pull request closed without merging**
