### PR TITLE
[WIP] Type annotation work

### PR DESCRIPTION
**Pull request by masaeedu**
As requested in https://github.com/minio/minio-js/issues/611#issuecomment-328707124, here's my (incomplete) work on converting the project to TypeScript with the goal of being able to produce accurate type annotations.

WIP for #611.

### CODE REVIEW

**Comment by harshavardhana** [comment]
This PR is not needed anymore since we have https://github.com/minio/minio-js#using-with-typescript ?? @krishnasrinivas @kaankabalak

**Comment by kaankabalak** [comment]
@harshavardhana I think they are separate as the commit you have linked creates the declaration file that describes the shape of the library; while this PR aims to migrate the existing code from JavaScript to TypeScript to easily catch errors/inconsistencies on code compilation and make the code more understandable.

**Comment by harshavardhana** [comment]
Then are we interested in continuing this work, since we haven't had any movement in this PR for past 3 months??

**Comment by kaankabalak** [comment]
@harshavardhana As the end goal was to produce the type annotations, and the link you gave accomplishes it, I think this issue can be closed. If we want to convert the project to TypeScript in the future for any reason, we can continue from this PR.

**Comment by masaeedu** [comment]
I'm not using the project anymore, so I'm not likely to be finishing these. Anyone else who wants to use this stuff is free to pick up where I left off.

**Pull request closed without merging**
