### PR TITLE
arguments: Take arguments like other libraries and validate them.

### PR DESCRIPTION
**Pull request by harshavardhana**
Add a new field 'transport' to params and avoid taking new arguments
for Client constructor.

### CODE REVIEW

**Comment by harshavardhana** [comment]
> is this being used anywhere?

This should be removed.

**Comment by harshavardhana** [comment]
> gulp test fails on 0.10.X you can add insecure: true to new Client to fix it (test.js:53) and re-enable builds for 0.10.X

Let me do that.

**Comment by harshavardhana** [comment]
> client.traceOn(process.stdout) needs to be removed

yes.

**Comment by harshavardhana** [comment]
Fixed all the comments and pushed. @krishnasrinivas

**Comment by krishnasrinivas** [comment]
I lost the network before I could make the following comment:

> Make `makeRequest`, `makeRequestStream`, `logHTTP` private methods.

I tried to fix the private methods issue but there is no good solution.

[Prefixing "_"](http://stackoverflow.com/questions/27849064/how-to-implement-private-method-in-es6-class-with-traceur) does not give privacy, it will still be accessible from outside. This is just the limitation of es6 classes.

Best option to solve the private methods problem is to do it the traditional javascript way:
```
var F = function() {
    var privateFn1 = () => {..}
    var privateFn2 = () => {..}
    var privateFn3 = () => {..}

    this.publicFn1 = () => {..}
    this.publicFn2 = () => {..}
    this.publicFn3 = () => {..}
}

var f = new F()
```

**Comment by harshavardhana** [comment]
> var F = function() {
>     var privateFn1 = () => {..}
>     var privateFn2 = () => {..}
>     var privateFn3 = () => {..}
> 
>     this.publicFn1 = () => {..}
>     this.publicFn2 = () => {..}
>     this.publicFn3 = () => {..}
> }
> 
> var f = new F()

Let do that in next patch.

**Pull request merged**
