### PR TITLE
examples: fix the examples so that they are uptodate with the recent API changes

### PR DESCRIPTION
**Pull request by krishnasrinivas**

### CODE REVIEW

**Comment by krishnasrinivas** [comment]
@harshavardhana it's stuck on continuous-integration/appveyor/branch — Waiting for status to be reported, any clues?

**Comment by harshavardhana** [comment]
Since we started throwing errors for any end point other than s3.amazonaws.com we should remove those references in our examples.

**Comment by harshavardhana** [comment]
@krishnasrinivas as practice do not merge your own commits.

**Comment by krishnasrinivas** [comment]
@harshavardhana ok

**Pull request merged**
