### PR TITLE
added tags response from listObjectsV2WithMetadata

### PR DESCRIPTION
**Pull request by TzachiSh**
split the UserTags from xml to object.

### CODE REVIEW

**Comment by prakashsvmx** [comment]
@TzachiSh  thank you for the contribution. Can you please resolve the lint/formatting CI failure ?

**Comment by prakashsvmx** [comment]
Could you please add a functional test @TzachiSh  ?

**Comment by TzachiSh** [comment]
> Could you please add a functional test @TzachiSh ?

Added

**Review by prakashsvmx — APPROVED** [review]

**Review by kaankabalak — APPROVED** [review]

**Comment by TzachiSh** [comment]
Hey anyone gonna to Marge it?

**Pull request merged**
