### PR TITLE
feature: add user defined metadata and content disposition to post policy

### PR DESCRIPTION
**Pull request by joaofranciscosantos**
This PR is to address https://github.com/minio/minio-js/issues/1034

Feel free to do whatever you want with this code sample. The package @types/minio would also need an update.

Test it well since I only spent a couple minutes on it. I might have missed something.

### CODE REVIEW

**Comment by joaofranciscosantos** [comment]
Just a small follow up.
I've being developing and testing with this branch. I've not encounter any problems so far using the presigned url.

Also, I've been mocking with these types
```javascript
setContentDisposition(type: string): void;
setUserMetaData(type: {[key: string]: string}): void;
```

References:
* https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#UserMetadata
* https://github.com/aws/aws-sdk-js-v3/blob/776214d2a5fba181fe883a19e93b4bfbf70d3cdc/clients/client-s3/src/models/models_1.ts#L401

**Review by prakashsvmx — CHANGES_REQUESTED** [review]
@joaofranciscosantos  Thank you for the contribution

Looks like the requests fail when setContentDisposition property is set.
e.g Without Content disposition

### Test code/Results.
<details>

```
var s3Client = new Minio.Client({
  useSSL:false,
  endPoint:"localhost",
  port:9000,
  accessKey:"minio",
  secretKey:"minio123"
})

// Construct a new postPolicy.
var policy = s3Client.newPostPolicy()
// Set the object name my-objectname.
policy.setKey("infra-policy.txt")
// Set the bucket to my-bucketname.
policy.setBucket("post-policy-test")

var expires = new Date()
expires.setSeconds(24 * 60 * 60 * 10) // 10 days
policy.setExpires(expires)

policy.setContentLengthRange(1, 1024*1024) // Min upload length is 1KB Max upload size is 1MB

policy.setContentType('text/plain')

//policy.setContentDisposition('attachment; filename=infra-policy.txt')

policy.setUserMetaData({
  "sph-meta": 'sph-value'
})

s3Client.presignedPostPolicy(policy, function(e, data) {
  if (e) return console.log(e)
  var curl = []
  curl.push(`curl ${data.postURL}`)
  for (var key in data.formData) {
    if (data.formData.hasOwnProperty(key)) {
      var value = data.formData[key]
      curl.push(`-F ${key}=${value}`)
    }
  }
  // Print curl command to upload files.
  curl.push('-F file=@<FILE>')
  console.log(curl.join(' '))
})
```

### CURL Request and the result

```
curl http://localhost:9000/post-policy-test -F key=infra-policy.txt -F bucket=post-policy-test -F Content-Type=text/plain -F x-amz-meta-sph-meta=sph-value -F x-amz-date=20220711T054027Z -F x-amz-algorithm=AWS4-HMAC-SHA256 -F x-amz-credential=minio/20220711/us-east-1/s3/aws4_request -F policy=eyJjb25kaXRpb25zIjpbWyJlcSIsIiRrZXkiLCJpbmZyYS1wb2xpY3kudHh0Il0sWyJlcSIsIiRidWNrZXQiLCJwb3N0LXBvbGljeS10ZXN0Il0sWyJjb250ZW50LWxlbmd0aC1yYW5nZSIsMSwxMDQ4NTc2XSxbImVxIiwiJENvbnRlbnQtVHlwZSIsInRleHQvcGxhaW4iXSxbImVxIiwiJHgtYW16LW1ldGEtc3BoLW1ldGEiLCJzcGgtdmFsdWUiXSxbImVxIiwiJHgtYW16LWRhdGUiLCIyMDIyMDcxMVQwNTQwMjdaIl0sWyJlcSIsIiR4LWFtei1hbGdvcml0aG0iLCJBV1M0LUhNQUMtU0hBMjU2Il0sWyJlcSIsIiR4LWFtei1jcmVkZW50aWFsIiwibWluaW8vMjAyMjA3MTEvdXMtZWFzdC0xL3MzL2F3czRfcmVxdWVzdCJdXSwiZXhwaXJhdGlvbiI6IjIwMjItMDctMjFUMDU6NDA6MDAuNDgxWiJ9 -F x-amz-signature=a7b3e93bec81e5d63b945c8f9f46f8aad1d88196abff727ac50579bd96c13908 -F file=@/tmp/infra-policy.txt


 mc ls local/post-policy-test
[2022-07-11 11:11:04 IST]   570B STANDARD infra-policy.txt


mc stat local/post-policy-test/infra-policy.txt 
Name      : infra-policy.txt
Date      : 2022-07-11 11:11:04 IST 
Size      : 570 B  
ETag      : 03d3126cfd88bf91438f1113eece66dc 
Type      : file 
Metadata  :
  X-Amz-Meta-Sph-Meta: sph-value 
  Content-Type       : text/plain 


```

### With content disposition
```

curl http://localhost:9000/post-policy-test -F key=infra-policy.txt -F bucket=post-policy-test -F Content-Type=text/plain -F Content-Disposition=attachment; filename=infra-policy.txt -F x-amz-meta-sph-meta=sph-value -F x-amz-date=20220711T054537Z -F x-amz-algorithm=AWS4-HMAC-SHA256 -F x-amz-credential=minio/20220711/us-east-1/s3/aws4_request -F policy=eyJjb25kaXRpb25zIjpbWyJlcSIsIiRrZXkiLCJpbmZyYS1wb2xpY3kudHh0Il0sWyJlcSIsIiRidWNrZXQiLCJwb3N0LXBvbGljeS10ZXN0Il0sWyJjb250ZW50LWxlbmd0aC1yYW5nZSIsMSwxMDQ4NTc2XSxbImVxIiwiJENvbnRlbnQtVHlwZSIsInRleHQvcGxhaW4iXSxbImVxIiwiJENvbnRlbnQtRGlzcG9zaXRpb24iLCJhdHRhY2htZW50OyBmaWxlbmFtZT1pbmZyYS1wb2xpY3kudHh0Il0sWyJlcSIsIiR4LWFtei1tZXRhLXNwaC1tZXRhIiwic3BoLXZhbHVlIl0sWyJlcSIsIiR4LWFtei1kYXRlIiwiMjAyMjA3MTFUMDU0NTM3WiJdLFsiZXEiLCIkeC1hbXotYWxnb3JpdGhtIiwiQVdTNC1ITUFDLVNIQTI1NiJdLFsiZXEiLCIkeC1hbXotY3JlZGVudGlhbCIsIm1pbmlvLzIwMjIwNzExL3VzLWVhc3QtMS9zMy9hd3M0X3JlcXVlc3QiXV0sImV4cGlyYXRpb24iOiIyMDIyLTA3LTIxVDA1OjQ1OjAwLjc1NloifQ== -F x-amz-signature=c2c787457e39f7cbccb3a1facc3e85aa76de51ffee6da628240bc91513f3dd2b -F file=@/tmp/infra-policy.txt
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AuthorizationQueryParametersError</Code><Message>Error parsing the X-Amz-Credential parameter; the Credential is mal-formed; expecting &#34;&lt;YOUR-AKID&gt;/YYYYMMDD/REGION/SERVICE/aws4_request&#34;.</Message><BucketName>post-policy-test</BucketName><Resource>/post-policy-test</Resource><RequestId>1700B02B36905A3B</RequestId><HostId>33b1421b-8351-4d36-aa6c-35a5e329f937</HostId></Error>

```
</details>

**Comment by joaofranciscosantos** [comment]
Could it be whitespaces in curl or special charater '-'? 

Whatever is inside "filename=" i had to escape special charaters in order to work.

**Review by ebozduman — CHANGES_REQUESTED** [review]
When I run the presigned post policy test with a request to rename the uploaded file, I get the following error:
`Error parsing the X-Amz-Credential parameter; the Credential is mal-formed`

Please run and add a test with
```
policy.setContentDisposition('attachment; filename=text.txt')
```

**Comment by joaofranciscosantos** [comment]
I'll separate setContentDisposition in different pull request.

**Comment by ebozduman** [comment]
@joaofranciscosantos 

May I ask why you want to separate the fix for `setContentDisposition` in a different PR?

After fixing the issue, adding a test with like spaces
```
policy.setContentDisposition("attachment;filename=  MyDoc u m  e   nt.json  ;")
```
and with special characters supported in object names would be nice.

**Comment by joaofranciscosantos** [comment]
> @joaofranciscosantos
> 
> May I ask why you want to separate the fix for `setContentDisposition` in a different PR?
> 
> After fixing the issue, adding a test with like spaces
> 
> ```
> policy.setContentDisposition("attachment;filename=  MyDoc u m  e   nt.json  ;")
> ```
> 
> and with special characters supported in object names would be nice.

done

**Comment by harshavardhana** [comment]
Please fix the conflicts @joaofranciscosantos thank you

**Comment by joaofranciscosantos** [comment]
> Please fix the conflicts @joaofranciscosantos thank you

done

**Comment by prakashsvmx** [comment]
Tested . Changes look good to me :+1: 

### Test Script details

<details>

```
const superagent = require('superagent')
const _ = require('lodash')

var s3Client = new Minio.Client({
  useSSL:false,
  endPoint:"localhost",
  port:22000,
  accessKey:"minio",
  secretKey:"minio123"
})

// Construct a new postPolicy.
var policy = s3Client.newPostPolicy()
// Set the object name my-objectname.
policy.setKey("infra-policy-new.txt")
// Set the bucket to my-bucketname.
policy.setBucket("post-policy-test")

var expires = new Date()
expires.setSeconds(24 * 60 * 60 * 10) // 10 days
policy.setExpires(expires)

policy.setContentLengthRange(1, 1024*1024) // Min upload length is 1KB Max upload size is 1MB

policy.setContentTypeStartsWith('image/jpeg')
policy.setContentDisposition('attachment; filename=äöüex ®©µÄÆÐÕæŒƕƩǅ 01000000 0x40 \u0040 amȡȹɆple&0a!-_.*\'()&$@=;:+,?<>.pdf')

policy.setUserMetaData({
  "sph-meta": 'sph-value',
  "filename-meta": 'My* Docume nt.json'
})


s3Client.presignedPostPolicy(policy, (e, data) => {
  if (e) {
    console.log("::Test URL::")
  }
  var req = superagent.post(data.postURL)
  _.each(data.formData, (value, key) => req.field(key, value))
  req.attach('file', Buffer.from(Buffer.alloc(1, 0)), 'test')
  req.end(function(e) {
    if (e) {
      console.log("1:Error...")
    }
    // s3Client.removeObject(bucketName, objectName, done)
  })
  req.on('error', e =>{
    console.log("2:Error",e)
  })
})
```
</details>

### Output
<details>

```
Name      : infra-policy-new.txt
Date      : 2022-08-05 16:52:06 IST 
Size      : 1 B    
ETag      : 93b885adfe0da089cdf634904fd59f71 
Type      : file 
Metadata  :
  X-Amz-Meta-Filename-Meta: My* Docume nt.json 
  Content-Type            : image/jpeg 
  Content-Disposition     : attachment; filename=äöüex ®©µÄÆÐÕæŒƕƩǅ 01000000 0x40 @ amȡȹɆple&0a!-_.*'()&$@=;:+,?<>.pdf 
  X-Amz-Meta-Sph-Meta     : sph-value 


```

**Review by prakashsvmx — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
